# https://ci.appveyor.com/tools/encrypt
environment:
    VSTSToken_dyneia:
        secure: Rw5H8FwdDIZDs62uO7n5nMKrlsg8m9SQjsrvdVEkN1KYGWHM95UCc34f3y89rAo2oAqQ2lMgdqOM/dtPbvsIWw==

os: unstable

install: 
    - cinst -y pester

build: false

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }