# https://ci.appveyor.com/tools/encrypt
environment:
    VSTSToken:
        secure: Rw5H8FwdDIZDs62uO7n5nMKrlsg8m9SQjsrvdVEkN1KYGWHM95UCc34f3y89rAo2oAqQ2lMgdqOM/dtPbvsIWw==

os: unstable

install: 
    - cinst -y pester

build: false

test_script:
    - ps: |
		# run tests
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile '.\TestsResults.xml' -PassThru
		
		# upload results to AppVeyor
        (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path '.\TestsResults.xml'))

		# if failures, quit to prevent publish
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }